name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 29.3
    - uses: actions/checkout@v4
    - name: Run tests
      run: make package-lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.1
          - 26.3
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - 29.3
          - release-snapshot
          - snapshot
    steps:
    - uses: cachix/install-nix-action@V27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v4
    - name: Install deps for tests
      run: nix profile install 'nixpkgs#direnv'
    - name: Run tests
      run: make compile test
